### ISSUE TITLE
[Crash] 1.18 Tessellating block model with botania

### ISSUE THREAD

**Issue by jarquafelmu** [eerussianguy/Better-Foliage#11]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Mod versions

Botania 1.18.1-429
Better Foliage v3.0.2

### Modloader version

Forge 39.1.2

### Modpack info

Briar Patch 2 - v3.03
https://www.curseforge.com/minecraft/modpacks/briar-patch-2

### The latest.log file

https://gist.github.com/jarquafelmu/f3dc11fc6367638723f3099c852c1189

### Issue description

I placed a floating Solegnolia flower to prevent certain dropped items from being picked up with the ring of magnets. As soon as it tried to render, I crashed.

This is on a dedicated server and when I attempted to rejoin the server I instantly crashed again because the flower it still there.

### Steps to reproduce

1. Install both Botania and Better Foliage Reborn
2. Make creative world
3. Place floating Solegnolia flower
4. ???
5. Crash

Referenced in botania's issue tracker at https://github.com/VazkiiMods/Botania/issues/4030

**Comment by eerussianguy** [comment]
Issue was tracked and discovered by forge. I believe was fixed by them as well.
