### ISSUE TITLE
Compatibility Request: BYG & Quark

### ISSUE THREAD

**Issue by Atlantispy** [eerussianguy/Better-Foliage#12]
Please could you consider doing compatibility for these two popular mods that add leave types.

Thanks

**Comment by Atlantispy** [comment]
I note that the mod description says "Atmospheric, Bayou Blues, BOP, Caves and Cliffs, and Quark." are natively compatible, but it doesn't seem to be working for me at least, even with BOP trees

**Comment by eerussianguy** [comment]
I know

**Comment by Enterprise12nx01** [comment]
so will this ever get fixed :(
