### ISSUE TITLE
Issue with snow layers on Podzol

### ISSUE THREAD

**Issue by Aerioos** [eerussianguy/Better-Foliage#16]
![cmNj9et](https://user-images.githubusercontent.com/54180288/178640667-d08ba796-12eb-4d33-8483-538dd33ba171.png)

Encountered this issue on 1.18.2

Seems to be creating a better foliage grass when no grass is present or should be created.

**Comment by eerussianguy** [comment]
Is this present on the latest version?

**Comment by Atlantispy** [comment]
Yes, I believe this happens with "Snow! Real Magic", though they'd have to confirm whether they have that installed.
