### ISSUE TITLE
incompatibility with mods with "Overlay" texture blocks ?

### ISSUE THREAD

**Issue by SwagRabbit** [eerussianguy/Better-Foliage#2]
Hi,

Some mods (like abundance and Biomes o plenty) implemented an "overlay" system for textures of their block, for the leaves block in particular, which give the possibility to get the leaves texture tinted in function of the biomes, and, have over this, an other texture which doesn't change in function of the biome.

Exemple:

Abundance:budding_redbud_leaves
Abundance:flowering_redbud_leaves
Biomesoplenty:flowering_oak_leaves

your mod doesn't seem to be able to handle this kind of texture overlay.

**Comment by eerussianguy** [comment]
Yeah I think what I will do is add a variant version of the leaves model that allows overlay.

**Comment by eerussianguy** [comment]
I added this in the new release.

"overlay" <-- resource location of overlay
"tintOverlay" <-- whether overlay is tinted (default false)
"tintLeaves" <-- whether leaves are tinted (default true)

**Comment by eerussianguy** [comment]
When you finish your compat edits, can you send them here so I can add them to the mod?
