### ISSUE TITLE
[1.19.3] Failure to load

### ISSUE THREAD

**Issue by NovaViper** [eerussianguy/Better-Foliage#28]
Hey, whenever i try to load v4.0.6, I instantly get this error as it tries to load up, and it leads me to a screen in Miencraft saying "Better Foilage has failed to load properly". Here is my error log: https://mclo.gs/jzRlfdI

Minecraft Version: 1.19.3
Forge version: 44.1.0

**Comment by eerussianguy** [comment]
this is because 4.0.6 is for 1.19.2

releasing a 1.19.3 version today
