### ISSUE TITLE
1.20.1 invalid mod file error

### ISSUE THREAD

**Issue by DakkPasserida** [eerussianguy/Better-Foliage#30]
Only this mod is loaded
here's the latest.log https://mclo.gs/3cQTZsi
![image](https://github.com/eerussianguy/Better-Foliage/assets/31828906/5d5d994d-79c4-4216-a47d-d197dbe949b1)
Minecraft version: 1.20.1
Forge version: 47.0.35

**Comment by flixzit** [comment]
still not working?

**Comment by LKD-PIX** [comment]
still brokey

**Comment by LKD-PIX** [comment]
You messed up "Implementation-Version:" in MANIFEST.MF something with your buildscript seems to be brokey in 1.20.1, it runs fine when changing it to "Implementation-Version: 1.20.1-5.0.0"

**Comment by eerussianguy** [comment]
fixed in new version
