### ISSUE TITLE
Dynamic trees compat

### ISSUE THREAD

**Issue by ghost** [eerussianguy/Better-Foliage#4]
please make the mod work with dynamic trees! thanks

![image](https://user-images.githubusercontent.com/82549089/141374958-078ed207-9a56-45f3-88ec-b3ad07fce61a.png)

**Comment by eerussianguy** [comment]
Maybe

**Comment by Enterprise12nx01** [comment]
also want this

**Comment by johanplima** [comment]
This would be the best thing ever, plsss
