### ISSUE TITLE
[Feature Request] Add Support for Enhanced Farming

### ISSUE THREAD

**Issue by paintballkev812** [eerussianguy/Better-Foliage#6]
Would it be possible to add support for [Enhanced Farming](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)? It appears all trees use the default oak leaves with the exception of the olive tree which uses acacia leaves. I was thinking you'd be able to use the stock oak and acacia 'fluff' without the need of any additional assets.

**Comment by eerussianguy** [comment]
will be in next update
