### ISSUE TITLE
Compatibility issue for BOP.

### ISSUE THREAD

**Issue by Muzikboxxx** [eerussianguy/Better-Foliage#8]
Hello! So I saw that this mod says it's compatible with Biomes o plenty but when I install it along with bop the textures are not working. Only the vanilla trees seem to work.

**Comment by eerussianguy** [comment]
Please position the mod resource pack above BOP in the list. I am also pushing a new version soon so let me know if that fixes anything.

**Comment by winnetrie83** [comment]
As of version betterfoliage-3.0.3.jar, this issue still persists.
